// Code generated by Prismic. DO NOT EDIT.

import Carousel from "./Carousel";
import ContentIndex from "./ContentIndex";
import Events from "./Events";
import Faq from "./Faq";
import Features from "./Features";
import FooterHeading from "./FooterHeading";
import FooterLinkBlock from "./FooterLinkBlock";
import FooterMultiColumn from "./FooterMultiColumn";
import Form from "./Form";
import Hero from "./Hero";
import ImageWithText from "./ImageWithText";
import OptOut from "./OptOut";
import Process from "./Process";
import RichText from "./RichText";
import Testimonial from "./Testimonial";

export const components = {
	carousel: Carousel,
	content_index: ContentIndex,
	events: Events,
	faq: Faq,
	features: Features,
	footer_heading: FooterHeading,
	footer_link_block: FooterLinkBlock,
	footer_multi_column: FooterMultiColumn,
	form: Form,
	hero: Hero,
	image_with_text: ImageWithText,
	opt_out: OptOut,
	process: Process,
	rich_text: RichText,
	testimonial: Testimonial
};