// Code generated by Prismic. DO NOT EDIT.

import BoardIndex from "./BoardIndex";
import Carousel from "./Carousel";
import CategoryList from "./CategoryList";
import ContentIndex from "./ContentIndex";
import Donation from "./Donation";
import EventDetails from "./EventDetails";
import Events from "./Events";
import Faq from "./Faq";
import Features from "./Features";
import FooterHeading from "./FooterHeading";
import FooterLinkBlock from "./FooterLinkBlock";
import FooterMultiColumn from "./FooterMultiColumn";
import Form from "./Form";
import Hero from "./Hero";
import ImageWithText from "./ImageWithText";
import OptOut from "./OptOut";
import PricingTier from "./PricingTier";
import Process from "./Process";
import RichText from "./RichText";
import Testimonial from "./Testimonial";

export const components = {
	board_index: BoardIndex,
	carousel: Carousel,
	category_list: CategoryList,
	content_index: ContentIndex,
	dontation: Donation,
	event_details: EventDetails,
	events: Events,
	faq: Faq,
	features: Features,
	footer_heading: FooterHeading,
	footer_link_block: FooterLinkBlock,
	footer_multi_column: FooterMultiColumn,
	form: Form,
	hero: Hero,
	image_with_text: ImageWithText,
	opt_out: OptOut,
	pricing_tier: PricingTier,
	process: Process,
	rich_text: RichText,
	testimonial: Testimonial
};